import type { Metadata } from "next";
import { getServerSession } from "next-auth";
import { SessionProvider } from "./components/SessionProvider";
import Header from "./components/Header";

import './globals.css'

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getServerSession();

  return (
    <html lang="en">
      <body className="min-h-screen flex flex-col">
        <SessionProvider session={session}>
          <Header />
          <main className="flex-1 bg-blue-100 p-2">
            {children}
          </main>
        </SessionProvider>
      </body>
    </html>
  );
}
